### ISSUE TITLE
Update script error on Windows

### ISSUE THREAD

**Issue by xJau** [fluttercommunity/font_awesome_flutter#176]
Hello there
I've tried to upgrade to the pro version for use light Font Awesome icons following the instrucions.
When I run the **_.bat_**  script always shows this error:
```
PS C:\Users\Mauri\Desktop\font_awesome_flutter-8.12.0> .\tool\update.bat
Custom icons.json found, using local data only.
Unhandled exception:
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("terms")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
#1      main (file:///C:/Users/Mauri/Desktop/font_awesome_flutter-8.12.0/tool/generate_font.dart:83:25)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
So I tried many times on many repository version but still having same issue.
Also used others FontAwesome version and linux script version but nothing fixed!

someone can help me ?

**Comment by michaelspiss** [comment]
Sorry for the late reply. It seems like something about your icons.json is off. Please make sure you copied the correct file from the metadata folder of your font awesome pro download.
