### ISSUE TITLE
Exception when executing configurator.bat

### ISSUE THREAD

**Issue by hackntest** [fluttercommunity/font_awesome_flutter#231]
Running configurator.bat throws a Handshake exception. Cloned the repo and ran it from the master branch, nothing else.

This is what I get:

```
Using font_awesome_flutter version 10.3.0
Downloading https://api.github.com/repos/fluttercommunity/font_awesome_flutter/releases

No icons.json found, updating free icons
Downloading https://api.github.com/repos/FortAwesome/Font-Awesome
Choosing branch "6.x" of repository https://github.com/FortAwesome/Font-Awesome
Downloading https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.x/metadata/icons.json
Unhandled exception:
HandshakeException: Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: self signed certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911:54)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:19)
<asynchronous suspension>
```

**Comment by michaelspiss** [comment]
Hi! Are you behind a proxy? `CERTIFICATE_VERIFY_FAILED: self-signed certificate` suggests so, as `githubusercontent.com`'s certificate is issued by DigiCert and not self-signed.

**Comment by michaelspiss** [comment]
Closing for now - if the issue persists, please reopen
